dist: trusty
sudo: required
language: java
#env:
# - IPADDR = /sbin/ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}'
before_script:
# - sudo add-apt-repository -y ppa:git-core/ppa
# - sudo curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
# - sudo apt-get update
# - sudo apt-get install xqilla
# - sudo apt-get -y install git
# - sudo apt-get -y install python-pip
# - sudo apt-get -y install nodejs
# - sudo apt-get -y install lynx
# - sudo apt-get -y install libxml2-utils
# - sudo pip install --upgrade git+https://github.com/Grunny/zap-cli.git
# - npm install -g wiki
# - wiki &
 - curl ipinfo.io/ip > ip.txt
 #- export IPADDRESS = $(curl "ipinfo.io/ip")
 #- echo $IPADDRESS
 - cat ip.txt
 ## this gets and starts the latest official release
 #- wget https://github.com/zaproxy/zaproxy/releases/download/2.7.0/ZAP_2.7.0_Linux.tar.gz
 #- tar zxvf ZAP_2.7.0_Linux.tar.gz
 #- ./ZAP_2.7.0/zap.sh -config api.key=12345 -port 8090 -daemon &
 
 ## This is gets and starts a weekly rolling release of ZAP
 ##TODO encrypt an official api key
 ##TODO verify SHA1 hash of zap download
# - wget https://raw.githubusercontent.com/zaproxy/zap-admin/master/ZapVersions.xml
# - export ZAP=$(xmllint --xpath "string(//url)" ZapVersions.xml) 
# - wget $ZAP
# - unzip ZAP_WEEKLY*.zip
# - ./ZAP_D*/zap.sh -config api.key=12345 -port 8090 -daemon &
 
 
 - sleep 30
script:
 #- export IPADDR=/sbin/ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}'
# - zap-cli -p 8090 --api-key 12345 spider http://localhost:3000
# - zap-cli -p 8090 --api-key 12345 active-scan http://localhost:3000
# - sudo zap-cli -p 8090 --api-key 12345 report -f html -o ./report.html
# - lynx ./report.html -dump
 #- cat ./report.xml
 #- cat ./report.html 

 
