dist: trusty
sudo: required
language: java
#env:
# - IPADDR = /sbin/ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}'
before_script:
 - sudo add-apt-repository -y ppa:git-core/ppa
 - sudo curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
 - sudo apt-get update
 - sudo apt-get install xqilla
 - sudo apt-get -y install git
 - sudo apt-get -y install python-pip
 - sudo apt-get -y install nodejs
 - sudo apt-get -y install lynx
 - sudo apt-get -y install libxml2-utils
 - sudo pip install --upgrade git+https://github.com/Grunny/zap-cli.git
 - npm install -g wiki
 - wiki &
 ## this gets and starts the latest official release
 #- wget https://github.com/zaproxy/zaproxy/releases/download/2.7.0/ZAP_2.7.0_Linux.tar.gz
 #- tar zxvf ZAP_2.7.0_Linux.tar.gz
 #- ./ZAP_2.7.0/zap.sh -config api.key=12345 -port 8090 -daemon &
 
 ## This is gets and starts a weekly rolling release of ZAP
 ##TODO encrypt an official api key
 - wget https://raw.githubusercontent.com/zaproxy/zap-admin/master/ZapVersions.xml
 - export ZAP=$(xmllint --xpath "string(//url)" ZapVersions.xml) 
 - wget $ZAP 
 - export SHA1_FROM_XML=$(xmllint --xpath "string(//hash)" ZapVersions.xml)
 - export SHA1_OF_FILE=$(sha1sum ZAP_WEEKLY_D*.zip)
 - test ${SHA1_FROM_XML:5} = ${SHA1_OF_FILE:0:40}
 - unzip ZAP_WEEKLY_D*.zip
 - ./ZAP_D*/zap.sh -config api.key=12345 -port 8090 -daemon &
 
 
 - sleep 30
script:
 ## The following needs tweeking to work with an encrypted checkin of a ZAP session 
 ## that includes a valid context with a user and password. The following entries are just examples 
 ## of what is needed
 ## commanline switches "-c" is context "-u" user "--recursive" means that it drill down into
 ## https://[the].[server].[name]/analyze/ and every link found on every page after "analyze"
 #- zap-cli -p 8090 --api-key 12345 session load /some_valid_session.session
 #- zap-cli -p 8090 --api-key 12345 spider -c my_awesome_context -u user@somemail.com https://[the].[server].[name]/analyze/
 #- zap-cli -p 8090 --api-key 12345 active-scan --recursive -c my_awesome_context -u user@somemail.com https://[the].[server].[name]/analyze/
 
 #- export IPADDR=/sbin/ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}'
 - zap-cli -p 8090  --api-key 12345 spider http://localhost:3000
 - zap-cli -p 8090  --api-key 12345 active-scan http://localhost:3000
 - sudo zap-cli -p 8090  --api-key 12345 report -f html -o ./report.md
 - lynx ./report.html -dump
 #- cat ./report.xml
 #- cat ./report.html 

 
