dist: trusty
sudo: required
language: java
before_script:
 - sudo add-apt-repository -y ppa:git-core/ppa
 - sudo curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
 - sudo apt-get update
 - sudo apt-get -y install git
 - sudo apt-get -y install python-pip
 - sudo apt-get -y install nodejs
 - sudo pip install --upgrade git+https://github.com/Grunny/zap-cli.git
 - npm install -g wiki
 - wiki
 - wget https://github.com/zaproxy/zaproxy/releases/download/2.5.0/ZAP_2.5.0_Linux.tar.gz
 - tar zxvf ZAP_2.5.0_Linux.tar.gz
 - ./ZAP_2.5.0_Linux/zap.sh -config api.key=12345 -port 8090 -daemon &
script:
 - zap-cli -p 8090 --api-key 12345 spider http://localhost:3000
 - zap-cli -p 8090 --api-key 12345 active-scan http://localhost:3000
 - sudo zap-cli -p 8090 --api-key 12345 report -f html -o ./report.html
 - cat ./report.html

 
