version: 0.2
secrets:
  nick_address: $NICK_ADDRESS
  nick_ssn: $NICK_SSN
phases:
  build:
    commands:
      - curl ifconfig.co
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files: 
    - hello
